version: "3.9"
services:
  app:
    container_name: "anovote_backend"
    env_file:
      - ./.env.docker
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - "./src:/app/src"
      - "./tsconfig.json:/app/tsconfig.json"
    networks:
      - anovote_backend
    working_dir: "/app"
    depends_on:
      - "db"
    command:
      [
        "denon",
        "run --unstable --config tsconfig.json --allow-read --allow-write --allow-net --allow-env ./src/main.ts",
      ]
  db:
    container_name: "anovote_rel_db"
    image: postgres
    ports:
      - "2345:5432"
    volumes:
      - anovote-data:/var/lib/postgresql
    networks:
      - anovote_backend
    env_file:
      - ./.env.docker

  db_mysql:
    container_name: "mysql"
    command: mysqld --default-authentication-plugin=mysql_native_password --max-allowed-packet=67108864
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./.env.mysql
    volumes:
      - data-mysql:/var/lib/mysql
    networks:
      - anovote_backend

volumes:
  data-mysql:
  anovote-data:
networks:
  anovote_backend:
