version: '3.9'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: source
        volumes:
            - './src:/app/src'
        ports:
            - '9229:9229'
            - '${WS_PORT}:${WS_PORT}'
    db:
        env_file:
            - '.env'
        ports:
            - '${DB_PORT}:5432'

    # certbot:
    #     image: certbot/certbot
    #     container_name: certbot
    #     depends_on:
    #         - nginx-proxy
    #     volumes:
    #         - ./ssl:/etc/letsencrypt
    #         - ./ssl-log:/var/log/letsencrypt
    #         - ./wwl/.well-known:/var/www/.well-known
    #     command: ['renew']
