version: '3.9'
services:
  app:
    container_name: 'anovote_backend'
    env_file:
      - .env.docker
    image: anovote:backend
    build: .
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
    volumes:
      - './logs:/app/logs'
    networks:
      - anovote_backend
    depends_on:
      - 'db'
  db:
    container_name: 'anovote_database'
    image: postgres
    volumes:
      - anovote-data:/var/lib/postgresql
    networks:
      - anovote_backend
    env_file:
      - .env.docker
volumes:
  anovote-data:
networks:
  anovote_backend:
