version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: source
    volumes:
      - "./src:/app/src"
    ports:
      - "9229:9229"
      - "${WS_PORT}:${WS_PORT}"
  db:
    env_file:
      - ".env"
    ports:
      - "${DB_PORT}:5432"
