version: '3.9'
services:
  app:
    container_name: 'anovote_backend'
    env_file:
      - .env.docker
    image: anovote:backend
    build: .
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
    volumes:
      - './logs:/app/logs'
    networks:
      - anovote_backend
    depends_on:
      - 'db'
  db:
    container_name: 'anovote_database'
    image: postgres
    volumes:
      - anovote-data:/var/lib/postgresql
    networks:
      - anovote_backend
    environment:
      TZ: 'Europe/Oslo'
    env_file:
      - .env.docker
  postgres_tests:
    container_name: 'test-db'
    image: postgres:11
    environment:
      POSTGRES_DB: '${DB_TEST_DATABASE}'
      POSTGRES_USER: '${DB_TEST_USER}'
      POSTGRES_PASSWORD: '${DB_TEST_PASSWORD}'
    ports:
      - ${DB_TEST_PORT}:${DB_TEST_PORT}
    command: -p ${DB_TEST_PORT}

volumes:
  anovote-data:
networks:
  anovote_backend:
