version: "3.9"
services:
  app:
    container_name: "anovote_backend"
    env_file:
      - .env
    image: anovote:backend
    build: .
    ports:
      - "8080:8080"
    networks:
      - anovote_backend
    depends_on:
      - "db"
  db:
    container_name: "anovote_database"
    image: postgres
    volumes:
      - anovote-data:/var/lib/postgresql
    networks:
      - anovote_backend
    env_file:
      - .env
volumes:
  anovote-data:
networks:
  anovote_backend:
