name: Deploy on autodeploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVERIP }}
          username: ${{ secrets.AUTODELPLOYUSERNAME }}
          password: ${{ secrets.SERVERUSERPASSWORD }}
          script: cd ${{ secrets.AUTODEPLOYPROJECTPATH }}/backend && git pull && docker-compose down && ./anovote prod -d
      - name: Trigger next workflow
        # https://stevenmortimer.com/running-github-actions-sequentially/
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-newman-check
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
