name: Deploy on autodeploy

on:
    push:
        branches: [main, bugfix/GHA-workflow]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Push to server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVERIP }}
                  username: ${{ secrets.AUTODELPLOYUSERNAME }}
                  password: ${{ secrets.SERVERUSERPASSWORD }}
                  script: cd ${{ secrets.AUTODEPLOYPROJECTPATH }}/backend && ./start-production.sh -b
            # We do not use postman any more so next workflow might cause problems
            #  - name: Trigger next workflow
            #   # https://stevenmortimer.com/running-github-actions-sequentially/
            #   if: success()
            #   uses: peter-evans/repository-dispatch@v1
            #   with:
            #     token: ${{ secrets.REPO_GHA_PAT }}
            #     repository: ${{ github.repository }}
            #     event-type: trigger-newman-check
            #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
