name: Deploy on autodeploy

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVERIP }}
          username: ${{ secrets.AUTODELPLOYUSERNAME }}
          password: ${{ secrets.SERVERUSERPASSWORD }}
          script: cd ${{ secrets.AUTODEPLOYPROJECTPATH }} && git pull
