name: Newman Run

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.postmanApiKey }}
          collection: 8579911-603f09aa-1eee-421d-b708-c6db344a9631
          environment: 8579911-7b9dd4e7-c4e3-456e-b44b-30009dcb05a7
